# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d18e2cf79009e12e8b74d3d7ea5a6aba"
name = "credit-app-partner"
application_url = "https://shopify-credit-app-frontend.onrender.com"
embedded = true
handle = "opentech-credit-app-test"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-credit-app-frontend.onrender.com/auth/callback",
  "https://shopify-credit-app-frontend.onrender.com/auth/shopify/callback",
  "https://shopify-credit-app-frontend.onrender.com/api/auth/callback",
]

# Metafields de cliente para documento de identidad
[customer.metafields.app.document_type]
type = "single_line_text_field"
name = "Tipo de Documento (Doc)"
access.admin = "merchant_read_write"

[customer.metafields.app.document_number]
type = "single_line_text_field"
name = "Número de Documento (N°)"
access.admin = "merchant_read_write"
