"""add_bank_name_to_payment

Revision ID: 025192e8ffa0
Revises: 9aa7a4a8741a
Create Date: 2026-05-13 20:51:21.969137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025192e8ffa0'
down_revision: Union[str, Sequence[str], None] = '9aa7a4a8741a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'document_number')
    op.drop_column('customers', 'document_type')
    op.add_column('payments', sa.Column('bank_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'bank_name')
    op.add_column('customers', sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('document_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
