"""upgrade credit and installment models

Revision ID: 0ae7f07d8683
Revises: 1bdfad55d26c
Create Date: 2025-11-18 20:59:52.277528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae7f07d8683'
down_revision: Union[str, Sequence[str], None] = '1bdfad55d26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_domain')
    )
    op.add_column('credits', sa.Column('merchant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_credits_invoice_number'), 'credits', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_credits_merchant_id'), 'credits', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'credits', 'merchants', ['merchant_id'], ['id'])
    op.add_column('customers', sa.Column('merchant_id', sa.UUID(), nullable=False))
    op.add_column('customers', sa.Column('shopify_customer_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('extra_data', sa.String(), nullable=True))
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_customers_shopify_customer_id'), 'customers', ['shopify_customer_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'merchants', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_shopify_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('customers', 'extra_data')
    op.drop_column('customers', 'shopify_customer_id')
    op.drop_column('customers', 'merchant_id')
    op.drop_constraint(None, 'credits', type_='foreignkey')
    op.drop_index(op.f('ix_credits_merchant_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_invoice_number'), table_name='credits')
    op.drop_column('credits', 'merchant_id')
    op.drop_table('merchants')
    # ### end Alembic commands ###
