"""add credits/installments/payments/history

Revision ID: 157176e33edf
Revises: a3605c95fef6
Create Date: 2025-11-20 22:06:34.808964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157176e33edf'
down_revision: Union[str, Sequence[str], None] = 'a3605c95fef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_installments', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('credit_installments', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('credit_installments', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('credit_installments', sa.Column('reference_number', sa.String(), nullable=True))
    op.add_column('credit_installments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('credit_installments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_credit_installments_credit_id'), 'credit_installments', ['credit_id'], unique=False)
    op.drop_constraint(op.f('credit_installments_credit_id_fkey'), 'credit_installments', type_='foreignkey')
    op.create_foreign_key(None, 'credit_installments', 'credits', ['credit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('credit_installments', 'is_paid')
    op.add_column('credits', sa.Column('invoice_code', sa.String(), nullable=True))
    op.add_column('credits', sa.Column('installments_count', sa.Integer(), nullable=False))
    op.add_column('credits', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('credits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('credits', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('credits', sa.Column('customer_document_id', sa.String(), nullable=True))
    op.add_column('credits', sa.Column('customer_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('credits', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('credits', 'balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_credits_invoice_number'), table_name='credits')
    op.create_index(op.f('ix_credits_customer_id'), 'credits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credits_invoice_code'), 'credits', ['invoice_code'], unique=False)
    op.drop_column('credits', 'invoice_number')
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('payments', 'reference_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_payments_credit_id'), 'payments', ['credit_id'], unique=False)
    op.drop_column('payments', 'bank_sender')
    op.drop_column('payments', 'document_id_sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('document_id_sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('bank_sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_credit_id'), table_name='payments')
    op.alter_column('payments', 'reference_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('payments', 'payment_method')
    op.add_column('credits', sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_credits_invoice_code'), table_name='credits')
    op.drop_index(op.f('ix_credits_customer_id'), table_name='credits')
    op.create_index(op.f('ix_credits_invoice_number'), 'credits', ['invoice_number'], unique=False)
    op.alter_column('credits', 'balance',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('credits', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('credits', 'customer_extra')
    op.drop_column('credits', 'customer_document_id')
    op.drop_column('credits', 'customer_name')
    op.drop_column('credits', 'updated_at')
    op.drop_column('credits', 'created_at')
    op.drop_column('credits', 'installments_count')
    op.drop_column('credits', 'invoice_code')
    op.add_column('credit_installments', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'credit_installments', type_='foreignkey')
    op.create_foreign_key(op.f('credit_installments_credit_id_fkey'), 'credit_installments', 'credits', ['credit_id'], ['id'])
    op.drop_index(op.f('ix_credit_installments_credit_id'), table_name='credit_installments')
    op.alter_column('credit_installments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('credit_installments', 'created_at')
    op.drop_column('credit_installments', 'reference_number')
    op.drop_column('credit_installments', 'paid_at')
    op.drop_column('credit_installments', 'paid_amount')
    op.drop_column('credit_installments', 'paid')
    # ### end Alembic commands ###
