"""initial migration

Revision ID: 1bdfad55d26c
Revises: 
Create Date: 2025-11-17 12:06:00.451607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdfad55d26c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('credit_reputation', sa.Enum('EXCELENTE', 'BUENA', 'REGULAR', 'MALA', name='creditreputation'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('EMITIDO', 'EN_PROCESO', 'CANCELADO', 'FINALIZADO', name='creditstatus'), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_table('credit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_history_id'), 'credit_history', ['id'], unique=False)
    op.create_table('credit_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_installments_id'), 'credit_installments', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('bank_sender', sa.String(), nullable=True),
    sa.Column('document_id_sender', sa.String(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('receipt_pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.ForeignKeyConstraint(['installment_id'], ['credit_installments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_credit_installments_id'), table_name='credit_installments')
    op.drop_table('credit_installments')
    op.drop_index(op.f('ix_credit_history_id'), table_name='credit_history')
    op.drop_table('credit_history')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
