"""Add_punctuality_tracking

Revision ID: 21b2856a6c66
Revises: 83099fc7b9bf
Create Date: 2026-03-09 19:53:04.664064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b2856a6c66'
down_revision: Union[str, Sequence[str], None] = '83099fc7b9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('punctuality_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('payments', sa.Column('punctuality_value', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'punctuality_value')
    op.drop_column('customers', 'punctuality_score')
    # ### end Alembic commands ###
