"""add notes to credits

Revision ID: 27d162d202c3
Revises: 95e9eaa4ab3a
Create Date: 2026-03-06 22:10:19.145108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27d162d202c3'
down_revision: Union[str, Sequence[str], None] = '95e9eaa4ab3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'notes')
    # ### end Alembic commands ###
