"""xxxx_soft_3

Revision ID: 3682970fe596
Revises: 14b360727865
Create Date: 2026-01-11 14:10:05.149412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3682970fe596'
down_revision: Union[str, Sequence[str], None] = '14b360727865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("credits", "customer_name")
    op.drop_column("credits", "customer_document_id")
    op.drop_column("credits", "customer_extra")


    # payments
    op.alter_column("payments", "merchant_id", nullable=False)

    # deleted_at (ejemplo para credits)
    for table in [
        "credits",
        "credit_installments",
        "credit_items",
        "payments",
    ]:
        op.add_column(table, sa.Column("deleted_at", sa.DateTime()))

    op.create_table(
        "products",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("unit_price", sa.Numeric(14,4), nullable=False),
        sa.Column("merchant_id", sa.UUID(as_uuid=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime, nullable=True),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"]),
    )

    op.create_index("ix_products_merchant_id", "products", ["merchant_id"])
