"""add_merchant_payment_settings

Revision ID: 36a8d6b69d54
Revises: 720ac11fef14
Create Date: 2026-03-10 12:49:43.117621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36a8d6b69d54'
down_revision: Union[str, Sequence[str], None] = '720ac11fef14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('pago_movil_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('merchants', sa.Column('transferencia_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'transferencia_settings')
    op.drop_column('merchants', 'pago_movil_settings')
    # ### end Alembic commands ###
