"""add_favorable_balance_to_customer

Revision ID: 4593319c2078
Revises: 27d162d202c3
Create Date: 2026-03-07 00:31:59.715030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4593319c2078'
down_revision: Union[str, Sequence[str], None] = '27d162d202c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'notes')
    op.add_column('customers', sa.Column('favorable_balance', sa.Numeric(precision=12, scale=2), nullable=True))
    op.execute("UPDATE customers SET favorable_balance = 0.00")
    op.alter_column('customers', 'favorable_balance', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'favorable_balance')
    op.add_column('credits', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
