"""Initial 3NF schema

Revision ID: 46303b6ccb36
Revises: 
Create Date: 2026-05-28 10:38:13.688226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46303b6ccb36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shop_domain', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_domain')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('shopify_customer_id', sa.BigInteger(), nullable=True),
    sa.Column('favorable_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('punctuality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_customers_shopify_customer_id'), 'customers', ['shopify_customer_id'], unique=False)
    op.create_table('merchant_payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('method_name', sa.String(), nullable=False),
    sa.Column('settings_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_payment_settings_merchant_id'), 'merchant_payment_settings', ['merchant_id'], unique=False)
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('installments_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE_ACTIVACION', 'EMITIDO', 'EN_PROGRESO', 'MOROSO', 'PAGADO', 'CANCELADO', name='creditstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_customer_id'), 'credits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_table('credit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_history_id'), 'credit_history', ['id'], unique=False)
    op.create_table('credit_installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'PAGADA', 'VENCIDO', 'CANCELADA', name='installmentstatus'), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_installments_id'), 'credit_installments', ['id'], unique=False)
    op.create_table('credit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False, comment='Shopify Product ID'),
    sa.Column('product_code', sa.String(), nullable=True, comment='SKU del producto'),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_items_id'), 'credit_items', ['id'], unique=False)
    op.create_index(op.f('ix_credit_items_product_id'), 'credit_items', ['product_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('REGISTRADO', 'APROBADO', 'RECHAZADO', 'EN_REVISION', 'CANCELADO', name='paymentstatus'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('punctuality_value', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installment_id'], ['credit_installments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('payment_installments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('installment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['credit_installments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id', 'installment_id')
    )
    op.create_table('payment_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('payment_proofs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['payment_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_proofs')
    op.drop_table('payment_tokens')
    op.drop_table('payment_installments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_credit_items_product_id'), table_name='credit_items')
    op.drop_index(op.f('ix_credit_items_id'), table_name='credit_items')
    op.drop_table('credit_items')
    op.drop_index(op.f('ix_credit_installments_id'), table_name='credit_installments')
    op.drop_table('credit_installments')
    op.drop_index(op.f('ix_credit_history_id'), table_name='credit_history')
    op.drop_table('credit_history')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_index(op.f('ix_credits_customer_id'), table_name='credits')
    op.drop_table('credits')
    op.drop_index(op.f('ix_merchant_payment_settings_merchant_id'), table_name='merchant_payment_settings')
    op.drop_table('merchant_payment_settings')
    op.drop_index(op.f('ix_customers_shopify_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
