"""add_unique_constraint_to_payment_reference

Revision ID: 4758d0e79b32
Revises: 4593319c2078
Create Date: 2026-03-07 16:47:20.491308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4758d0e79b32'
down_revision: Union[str, Sequence[str], None] = '4593319c2078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Resolve existing duplicates by appending '-DUP' + ID to the reference number
    op.execute(
        sa.text("""
            UPDATE payments
            SET reference_number = reference_number || '-FIX' || id
            WHERE id IN (
                SELECT id
                FROM (
                    SELECT id,
                           ROW_NUMBER() OVER (
                               PARTITION BY merchant_id, reference_number 
                               ORDER BY created_at
                           ) as row_num
                    FROM payments
                ) t
                WHERE t.row_num > 1
            )
        """)
    )
    # 2. Create the unique constraint
    op.create_unique_constraint('uq_payment_reference', 'payments', ['merchant_id', 'reference_number'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_reference', 'payments', type_='unique')
    # ### end Alembic commands ###
