"""Add installments_covered to Payment

Revision ID: 720ac11fef14
Revises: ee9d092a2397
Create Date: 2026-03-10 00:40:39.028194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720ac11fef14'
down_revision: Union[str, Sequence[str], None] = 'ee9d092a2397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('installments_covered', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'installments_covered')
    # ### end Alembic commands ###
