"""Cleanup unused columns and Product table

Revision ID: 83099fc7b9bf
Revises: 4758d0e79b32
Create Date: 2026-03-08 16:43:10.533665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83099fc7b9bf'
down_revision: Union[str, Sequence[str], None] = '4758d0e79b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_credits_invoice_code'), table_name='credits')
    op.drop_column('credits', 'invoice_code')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credits', sa.Column('invoice_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_credits_invoice_code'), 'credits', ['invoice_code'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=14, scale=4), autoincrement=False, nullable=False),
    sa.Column('merchant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('products_merchant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###
