"""refactor_customer_strict_fields_final

Revision ID: 95e9eaa4ab3a
Revises: 3682970fe596
Create Date: 2026-02-25 11:54:25.502992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95e9eaa4ab3a'
down_revision: Union[str, Sequence[str], None] = '3682970fe596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_history', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('credit_installments', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_credit_installments_credit_id'), table_name='credit_installments')
    op.drop_column('credit_installments', 'paid_at')
    op.drop_column('credit_installments', 'created_at')
    op.drop_column('credit_installments', 'reference_number')
    op.drop_column('credit_installments', 'paid_amount')
    op.drop_column('credit_installments', 'paid')
    op.alter_column('credit_items', 'product_id',
               existing_type=sa.VARCHAR(),
               comment='Shopify Product ID',
               existing_nullable=False)
    op.alter_column('credit_items', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='SKU del producto')
    op.create_index(op.f('ix_credit_items_id'), 'credit_items', ['id'], unique=False)
    op.create_index(op.f('ix_credit_items_product_id'), 'credit_items', ['product_id'], unique=False)
    op.drop_constraint(op.f('credit_items_credit_id_fkey'), 'credit_items', type_='foreignkey')
    op.create_foreign_key(None, 'credit_items', 'credits', ['credit_id'], ['id'], ondelete='CASCADE')
    op.drop_column('credit_items', 'deleted_at')
    op.alter_column('credits', 'installments_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('credits', 'status',
               existing_type=postgresql.ENUM('PENDIENTE_ACTIVACION', 'EMITIDO', 'EN_PROGRESO', 'MOROSO', 'PAGADO', 'CANCELADO', name='creditstatus'),
               nullable=False)
    op.drop_column('credits', 'updated_at')
    op.drop_column('customers', 'credit_reputation')
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payments_credit_id'), table_name='payments')
    op.drop_constraint(op.f('payments_installment_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('payments_credit_id_fkey'), 'payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_payments_installment'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'credits', ['credit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'credit_installments', ['installment_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_installment'), 'payments', 'credit_installments', ['installment_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('payments_credit_id_fkey'), 'payments', 'credits', ['credit_id'], ['id'])
    op.create_foreign_key(op.f('payments_installment_id_fkey'), 'payments', 'credit_installments', ['installment_id'], ['id'])
    op.create_index(op.f('ix_payments_credit_id'), 'payments', ['credit_id'], unique=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('customers', sa.Column('credit_reputation', postgresql.ENUM('EXCELENTE', 'BUENA', 'REGULAR', 'MALA', name='creditreputation'), autoincrement=False, nullable=True))
    op.add_column('credits', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('credits', 'status',
               existing_type=postgresql.ENUM('PENDIENTE_ACTIVACION', 'EMITIDO', 'EN_PROGRESO', 'MOROSO', 'PAGADO', 'CANCELADO', name='creditstatus'),
               nullable=True)
    op.alter_column('credits', 'installments_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('credit_items', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'credit_items', type_='foreignkey')
    op.create_foreign_key(op.f('credit_items_credit_id_fkey'), 'credit_items', 'credits', ['credit_id'], ['id'])
    op.drop_index(op.f('ix_credit_items_product_id'), table_name='credit_items')
    op.drop_index(op.f('ix_credit_items_id'), table_name='credit_items')
    op.alter_column('credit_items', 'product_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='SKU del producto')
    op.alter_column('credit_items', 'product_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Shopify Product ID',
               existing_nullable=False)
    op.add_column('credit_installments', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_credit_installments_credit_id'), 'credit_installments', ['credit_id'], unique=False)
    op.alter_column('credit_installments', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('credit_history', 'deleted_at')
    # ### end Alembic commands ###
