"""Add merchant_id to AuditLog

Revision ID: 96059de166c1
Revises: 5f8c42f5ac20
Create Date: 2026-04-08 23:37:19.163038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96059de166c1'
down_revision: Union[str, Sequence[str], None] = '5f8c42f5ac20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Session')
    op.add_column('audit_logs', sa.Column('merchant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'merchant_id')
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shop', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('isOnline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.Column('accessToken', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('accountOwner', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collaborator', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('refreshTokenExpires', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Session_pkey'))
    )
    # ### end Alembic commands ###
