"""Add document_type and document_number to customer

Revision ID: 9aa7a4a8741a
Revises: 96059de166c1
Create Date: 2026-04-24 11:51:14.257244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa7a4a8741a'
down_revision: Union[str, Sequence[str], None] = '96059de166c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Session')
    op.add_column('customers', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('document_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'document_number')
    op.drop_column('customers', 'document_type')
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shop', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isOnline', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accessToken', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('firstName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accountOwner', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('locale', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('collaborator', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('refreshToken', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refreshTokenExpires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Session_pkey'))
    )
    # ### end Alembic commands ###
