"""Add document_type and document_number to customer

Revision ID: 9aa7a4a8741a
Revises: 96059de166c1
Create Date: 2026-04-24 11:51:14.257244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa7a4a8741a'
down_revision: Union[str, Sequence[str], None] = '96059de166c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('document_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'document_number')
    op.drop_column('customers', 'document_type')
    # ### end Alembic commands ###
