"""Fix extra_data to JSONB

Revision ID: a3605c95fef6
Revises: 0ae7f07d8683
Create Date: 2025-11-19 23:48:22.036608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3605c95fef6'
down_revision: Union[str, Sequence[str], None] = '0ae7f07d8683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE customers 
            ALTER COLUMN extra_data 
            TYPE jsonb 
            USING extra_data::jsonb
        """)
    
    op.add_column('merchants', sa.Column('shop_domain', sa.String(), nullable=True))
    op.execute("UPDATE merchants SET shop_domain = 'placeholder.myshopify.com' WHERE shop_domain IS NULL")
    op.alter_column('merchants', 'shop_domain', nullable=False)
    op.add_column('merchants', sa.Column('access_token', sa.String(), nullable=True))
    op.drop_constraint(op.f('merchants_shop_domain_key'), 'merchants', type_='unique')
    op.create_unique_constraint(None, 'merchants', ['shop_domain'])
    op.drop_column('merchants', 'shopify_access_token')
    op.drop_column('merchants', 'shopify_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE customers 
        ALTER COLUMN extra_data 
        TYPE text 
        USING extra_data::text
        """)
    op.add_column('merchants', sa.Column('shopify_domain', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('merchants', sa.Column('shopify_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'merchants', type_='unique')
    op.create_unique_constraint(op.f('merchants_shop_domain_key'), 'merchants', ['shopify_domain'], postgresql_nulls_not_distinct=False)
    op.drop_column('merchants', 'access_token')
    op.drop_column('merchants', 'shop_domain')
    op.alter_column('customers', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
