"""replace_soft_deletes_with_audit_log

Revision ID: e1bc1cf0d6b9
Revises: ca14c9b8f322
Create Date: 2026-03-12 19:05:25.947435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1bc1cf0d6b9'
down_revision: Union[str, Sequence[str], None] = 'ca14c9b8f322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_history', 'deleted_at')
    op.drop_column('credit_installments', 'deleted_at')
    op.drop_column('credits', 'deleted_at')
    op.drop_column('payments', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credits', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credit_history', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
