"""add credit_items table

Revision ID: ec107b0ed805
Revises: 7e83d122d732
Create Date: 2025-12-28 13:29:26.984642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec107b0ed805'
down_revision: Union[str, Sequence[str], None] = '7e83d122d732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'credit_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('credit_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.String(), nullable=False),
        sa.Column('product_code', sa.String(), nullable=False),
        sa.Column('product_name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Numeric(12,2), nullable=False),
        sa.Column('total_price', sa.Numeric(12,2), nullable=False),
        sa.ForeignKeyConstraint(['credit_id'], ['credits.id']),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_installment_id_fkey'), 'payments', 'credit_installments', ['installment_id'], ['id'])
    op.create_foreign_key(op.f('payments_credit_id_fkey'), 'payments', 'credits', ['credit_id'], ['id'])
    op.create_foreign_key(op.f('fk_payments_installment'), 'payments', 'credit_installments', ['installment_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_payments_credit_id'), 'payments', ['credit_id'], unique=False)
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('REGISTRADO', 'APROBADO', 'RECHAZADO', 'EN_REVISION', name='paymentstatus', native_enum=False),
               type_=postgresql.ENUM('EN_REVISION', 'APROBADO', 'RECHAZADO', name='paymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'EN_REVISION'::paymentstatus"))
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('credits', 'status',
               existing_type=postgresql.ENUM('PENDIENTE_ACTIVACION', 'EMITIDO', 'EN_PROGRESO', 'MOROSO', 'PAGADO', 'CANCELADO', name='creditstatus'),
               nullable=True)
    op.alter_column('credits', 'installments_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('credit_installments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('paid_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('paid_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credit_installments', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_credit_installments_credit_id'), 'credit_installments', ['credit_id'], unique=False)
    op.alter_column('credit_installments', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('credit_installments', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
