"""Add paid columns to CreditInstallment

Revision ID: ee9d092a2397
Revises: 21b2856a6c66
Create Date: 2026-03-10 00:07:43.328948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee9d092a2397'
down_revision: Union[str, Sequence[str], None] = '21b2856a6c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_installments', sa.Column('paid', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('credit_installments', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('credit_installments', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_installments', 'paid_at')
    op.drop_column('credit_installments', 'paid_amount')
    op.drop_column('credit_installments', 'paid')
    # ### end Alembic commands ###
