# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d18e2cf79009e12e8b74d3d7ea5a6aba"
name = "credit-app-partner"
application_url = "https://adaptation-spokesman-frequent-obtain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers, read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://adaptation-spokesman-frequent-obtain.trycloudflare.com/auth/callback" ]

# En shopify.app.toml o shopify.app.dev-sin-partner.toml
